### ISSUE TITLE
User Interface Mockup and Storyboard

### ISSUE THREAD

**Issue by cujomalainey** [CMPUT301F16T13/ThunderCab#2]

**Comment by cujomalainey** [comment]
I am backup on this

**Comment by cujomalainey** [comment]
@JesseFarebro It would be awesome if this could be done by EOD, so we can review it before submitting it

**Comment by JesseFarebro** [comment]
Storyboard and mock ups are live on the wiki [here](https://github.com/CMPUT301F16T13/ThunderCab/wiki/Mockups).
