### ISSUE TITLE
ShowDriverAMapForARequest

### ISSUE THREAD

**Issue by cujomalainey** [CMPUT301F16T13/ThunderCab#40]

**Comment by JesseFarebro** [comment]
Are we talking about giving the driver a map once he's accepted a request to navigate to the user?

Using intents for now?

**Comment by icydusk** [comment]
Yes and yes. Probably a "see route" button

**Comment by JesseFarebro** [comment]
Moving to Part 5 to do work with static map images.

**Comment by cujomalainey** [comment]
requirement label removed, moving this to a "do if there is time"

**Comment by cujomalainey** [comment]
Removing people assigned, this has been pushed back to project till project part 6 until further notice
