### ISSUE TITLE
RequestParamSearchAddress

### ISSUE THREAD

**Issue by icydusk** [CMPUT301F16T13/ThunderCab#48]

**Comment by BottledTime** [comment]
I can easily search for exact address strings. I do not know how to search for requests near an address, which the user story also asks for. I'm pretty sure elasticsearch can only take coordinates. How are we handling this? Is this part of the story covered by what the navigation screen can do? @JesseFarebro? Or do we want them to be able to search for requests near given addresses through the advanced search as well?
