### ISSUE TITLE
Test Cases

### ISSUE THREAD

**Issue by cujomalainey** [CMPUT301F16T13/ThunderCab#5]
Holding off until UC are done.

**Comment by cujomalainey** [comment]
waiting on #1

**Comment by cujomalainey** [comment]
This will be done in the spare time in the lab

**Comment by cujomalainey** [comment]
Request tests are done, @icydusk what other tests are left for the model?

**Comment by icydusk** [comment]
Working on Car Tests

**Comment by cujomalainey** [comment]
Working on UserTests
