### ISSUE TITLE
ViewRequests

### ISSUE THREAD

**Issue by cujomalainey** [CMPUT301F16T13/ThunderCab#8]

**Comment by cujomalainey** [comment]
Geospatial searching is done, just need a way to lat and long to search with. 

@JesseFarebro just an fyi for after nav UI is done 

considering kicking this to part 5

**Comment by JesseFarebro** [comment]
I think we should kick it to part 5, I can do some cool stuff with displaying the geospatial data on the map view.

**Comment by cujomalainey** [comment]
Location and radius needs to be able to search at

**Comment by cujomalainey** [comment]
#24 links closely with that issue, keep in contact with @BottledTime to make sure that you don't duplicate work

**Comment by JesseFarebro** [comment]
@cujomalainey can we schedule a day to go to the library to crank this out because I'll need some guiding with what you've done so far.

**Comment by cujomalainey** [comment]
@JesseFarebro yep, or you can come to my place saturday and work
