### ISSUE TITLE
New requests are not seen by other users/App crashes when accepting.

### ISSUE THREAD

**Issue by BottledTime** [CMPUT301F16T13/ThunderCab#84]
1. Make a request.
2. Change to another user that’s a driver.
3. Go to the Requests page.
4. Go to Open Requests.
5. Verify that you can’t see the new request.
6. If you can see it, try to accept it. This should crash the app.

**Comment by JesseFarebro** [comment]
@BottledTime is this newly introduced or did it exist before ?

**Comment by BottledTime** [comment]
I don't know if it existed before. I just noticed it now. Vitor was able to replicate it.

**Comment by BottledTime** [comment]
The app crashing part seemed to be caused by calling isDriver() on a null object somewhere (I couldn't find it). I tried to replicate it and then found that I couldn't see new requests.

**Comment by JesseFarebro** [comment]
@BottledTime okay I think I know why that's happening, not being able to see requests could be because the requests are hard coded to only geosearch on some location Curtis had in Asia? Or is your issue more than that?

**Comment by BottledTime** [comment]
Oh, yeah, I changed it and it worked. Sorry for the alarm.
